# Generated by Django 4.1.2 on 2022-11-10 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filtros", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Filtros",
        ),
    ]
