# Generated by Django 4.1.2 on 2022-10-30 20:42

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bens", "0003_alter_category_options_alter_product_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Uso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("email", models.EmailField(max_length=250)),
                ("motivo", models.CharField(max_length=250)),
                ("mensagem", models.TextField(max_length=3000)),
                ("image", models.ImageField(blank=True, upload_to="uso/%Y/%m/%d")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="bem", unique=True
                    ),
                ),
                (
                    "bem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uso",
                        to="bens.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "solicitação",
                "verbose_name_plural": "solicitações",
                "ordering": ("bem",),
            },
        ),
        migrations.CreateModel(
            name="Erro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("email", models.EmailField(max_length=250)),
                ("mensagem", models.TextField(max_length=3000)),
                ("image", models.ImageField(blank=True, upload_to="erro/%Y/%m/%d")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="bem", unique=True
                    ),
                ),
                (
                    "bem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="erro",
                        to="bens.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "erro",
                "verbose_name_plural": "erros",
                "ordering": ("bem",),
            },
        ),
    ]
