# Generated by Django 4.1.2 on 2022-10-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="local",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="setor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
