# Generated by Django 4.1.2 on 2022-10-30 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bens", "0002_alter_product_local_alter_product_setor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "categoria",
                "verbose_name_plural": "categorias",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("slug",),
                "verbose_name": "imobilizado",
                "verbose_name_plural": "imobilizados",
            },
        ),
    ]
