# Generated by Django 4.1.2 on 2022-11-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bens", "0003_alter_category_options_alter_product_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="codbem",
            new_name="codigo",
        ),
        migrations.AddField(
            model_name="product",
            name="responsavel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
