# Generated by Django 4.1.2 on 2022-11-02 15:20

import bens.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bens", "0005_alter_product_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload", models.FileField(upload_to=bens.models.user_directory_path)),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, upload_to=bens.models.user_directory_path
            ),
        ),
    ]
