# Generated by Django 4.1.2 on 2022-11-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bens", "0006_mymodel_alter_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="categoria",
            new_name="CATEGORIA",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="codigo",
            new_name="CODIGO",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="descricao",
            new_name="DESCRICAO",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="local",
            new_name="LOCAL",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="responsavel",
            new_name="RESPONSAVEL",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="setor",
            new_name="SETOR",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="tag",
            new_name="TAG",
        ),
    ]
