# Generated by Django 4.1.2 on 2022-11-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bens", "0007_rename_categoria_product_categoria_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="CATEGORIA",
            new_name="categoria",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="CODIGO",
            new_name="codigo",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="DESCRICAO",
            new_name="descricao",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="LOCAL",
            new_name="local",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="RESPONSAVEL",
            new_name="responsavel",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="SETOR",
            new_name="setor",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="TAG",
            new_name="tag",
        ),
    ]
