# Generated by Django 4.1.2 on 2022-11-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bens", "0008_rename_categoria_product_categoria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="data_inicial",
            field=models.DateField(blank=True, null=True),
        ),
    ]
