# Generated by Django 4.1.2 on 2022-11-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bens", "0009_product_data_inicial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="data_final",
            field=models.DateField(blank=True, null=True),
        ),
    ]
